<section class="add-presta add-product">
    <h3>Ajout d'un produit</h3>
    <p>Ici vous trouvez le formulaire pour ajouter un produit dans la boutique pour l'utilisateur.</p>
    <div class="container-form">
        <form action="index.php?action=insertProductShop" class="submit-add-presta contact-form" method="POST" enctype="multipart/form-data">
            <div class="form-group">
                <label for="nom">Nom :</label>
                <input type="text" name="name" id="nom" placeholder="Nom du produit">
            </div>
            <div class="form-group">
                <label for="price">Prix :</label>
                <input type="text" name="price" id="price" placeholder="Prix du produit">
            </div>
            <div class="form-group">
                <label for="description">Description :</label>
                <textarea name="description" id="description" cols="30" rows="10" placeholder="Description du produit"></textarea>
            </div>
            <div class="form-group">
                <label for="picture">Photo :</label>
                <input type="file" name="picture" id="picture">
            </div>
            <input class="input-contact-form" type="submit" value="Crée le produit">
        </form>
    </div>
</section>