<div class="basket manage-shop">
    <?php foreach ($displayProductsShop as $displayProductShop) : ?>
        <tr>
            <td><img src="www/img/images-shop/<?= $displayProductShop["Photo"] ?>" alt="picture-product"></td>
            <td data-label="Designation :"><?= $displayProductShop["Produit"] ?></td>
            <td data-label="Description :"><?= $displayProductShop["Description"] ?></td>
            <td data-label="Prix :"><?= $displayProductShop["Prix"] . "€" ?></td>
            <td data-label="Action :" class="container-btn">
                <a href="index.php?action=updateProductShop&idProduct=<?= $displayProductShop["ID"] ?>"><i class="fas fa-pencil-alt"></i></a>
                <a href="index.php?action=deleteProductShop&delId=<?= $displayProductShop["ID"] ?>&picture=<?= $displayProductShop["Photo"] ?>"><i class="fas fa-times"></i></a>
            </td>
        </tr>
    <?php endforeach ?>
</div>