<form class="form-connect-user form-forgot-password" action="#" method="post">
    <fieldset>
        <legend>Récuperation du mot de passe</legend>
        <div class="container-logo">
            <a href="index.php"><img id="logo" class="logo" src="www/img/LBPI-1.png" alt="logo" /></a>
        </div>
        <div>
            <p>Merci de bien vouloir nous indiquer l'adresse mail utilisée pour la création de votre compte.</p>
            <p>Un lien de réinitailisation vous sera envoyé, il ne sera actif que pour une durée de 3h.</p>
        </div>
        <div>
            <label for="mail"></label>
            <input type="text" name="email" id="mail" placeholder="E-mail" required>
        </div>
        <input class="btn-submit-form" type="submit" value="Envoyer">
    </fieldset>
</form>