<page>

    <style type="text/css">
        page {
            width: 100%;
        }

        table {
            margin: auto;
            width: 100%;
            color: #717375;
            font-family: helvetica;
            line-height: 5mm;
            border-collapse: collapse;
        }

        img {
            width: 200px;
        }

        h2 {
            margin: 0;
            padding: 0;
        }

        p {
            margin: 5px;
            color: #717375;
            font-size: 16px;
        }

        .user {
            margin-top: 20px;
            margin-bottom: 10px;
        }

        .invoice {
            text-align: right;
            margin-top: 10px;
            margin-bottom: 20px;

        }

        .tr {
            text-align: right;
        }

        .border {
            margin-bottom: 15px;
        }

        .border th {
            border: 1px solid #000;
            color: white;
            background: #000;
            padding: 10px;
            font-weight: normal;
            font-size: 14px;
            text-align: center;
        }

        .border td {
            border: 1px solid #CFD1D2;
            padding: 10px;
            text-align: center;
        }

        .no-border {
            border: none;
            text-align: left;
            color: green;
        }

        .p-20 {
            width: 20%;
        }

        .p-33 {
            width: 33%;
        }

        .p-45 {
            width: 45%;
        }
    </style>

    <page_footer>
        <p>La P'tite boutique SA</p>
        <p>Capital de 10000€</p>
        <p>6 impasse ampère</p>
        <p>28100 Dreux </p>
        <p>Siret 122 454 554 55898</p>
    </page_footer>

    <div>
        <img class="logo" src="www/img/LBPI-1.png" alt=logo />
    </div>

    <div>
        <div class="user">
            <p>Facturé à :</p>
            <p><?= $dataUser["Nom"] . " " . $dataUser["Prenom"] ?> </p>
            <p><?= $dataUser["Adresse"] ?></p>
            <p><?= $dataUser["Code_postal"] . " " . $dataUser["Ville"] ?></p>
        </div>

        <div class="invoice">
            <p>Date de facturation : <?= $invoice["Date"] ?></p>
            <p>Numéro de facture : <?= $invoice["ID"] ?></p>
        </div>
    </div>

    <table class="border">
        <thead>
            <tr>
                <th class="p-33">
                    Produit
                </th>
                <th class="p-20">
                    Quantité
                </th>
                <th class="p-20">
                    Prix unitaire TTC
                </th>
                <th class="p-20">
                    Total TTC
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($products as $product) : ?>
                <tr>
                    <td>
                        <?= $product["Produit"] ?>
                    </td>
                    <td>
                        <?= $product["Quantite"] ?>
                    </td>
                    <td>
                        <?= number_format($product["Prix_unitaire"], 2) ?> €
                    </td>
                    <td>
                        <?= number_format(($product["Prix_unitaire"] * $product["Quantite"]), 2) ?> €
                    </td>
                </tr>
            <?php endforeach; ?>
            <tr>
                <td class="no-border tr">
                    Total HT : <?= number_format($product["Prix_total"] - ($product["Prix_total"] * 0.2), 2) ?> €
                </td>
            </tr>
            <tr>
                <td class="no-border tr">
                    TVA (20%) : <?= number_format(($product["Prix_total"] * 0.2), 2) ?> €
                </td>

            </tr>
            <tr>
                <td class="no-border tr">
                    Total TTC : <?= number_format($product["Prix_total"], 2)  ?> €
                </td>
            </tr>
        </tbody>
    </table>
</page>