<section class="areaUser information-user update">
    <div class="container-information">
        <nav>
            <ul>
                <li class="myOrder"><a href="index.php?action=detailslastOrder&idLastOrder=<?= $lastOrder["ID_commande"] ?>">Mes commandes</a></li>
                <li class="myInformations"><a href="index.php?action=displayInformationUser">Mes informations personnelles</a></li>
            </ul>
        </nav>
        <div class="container-update">
            <h3>Modifier l'email</h3>
            <div class="container-txt-update">
                <p>Utilisez le formulaire ci-dessous pour modifier l'e-mail de votre compte.</p>
                <p> Utilisez ce nouvel e-mail lors de votre prochaine connexion.</p>
            </div>
            <div>
                <p class="bold-text">Ancien e-mail :</p>
                <p><span><?= $infoUser["Mail"] ?></span></p>
            </div>
            <form action="index.php?action=updateDataUser&mail" method="post">
                <div class="form-group">
                    <label for="mail">Nouvel e-mail :</label>
                    <input type="text" name="mail" id="mail">
                </div>
                <div class="form-group">
                    <label for="mail-confirm">Ressaisir le nouvel email :</label>
                    <input type="text" name="mail-confirm" id="mail-confirm">
                </div>
                <div class="form-group">
                    <label for="check-password">Mot de passe actuel :</label>
                    <input type="password" name="password" id="check-password">
                </div>
                <input class="update-btn input-update" type="submit" value="Enregistrer la modification">
            </form>
        </div>
    </div>
</section>