<section class="areaUser information-user update">
    <div class="container-information">
        <nav>
            <ul>
                <li class="myOrder"><a href="index.php?action=detailslastOrder&idLastOrder=<?= $lastOrder["ID_commande"] ?>">Mes commandes</a></li>
                <li class="myInformations"><a href="index.php?action=displayInformationUser">Mes informations personnelles</a></li>
            </ul>
        </nav>
        <div class="container-update">
            <h3>Modifier le mot de passe :</h3>
            <div class="container-txt-update">
                <p>Utilisez le formulaire ci-dessous pour modifier le mot de passe de votre compte.</p>
                <p> Utilisez ce nouveau mot de passe lors de votre prochaine connexion.</p>
            </div>
            <div>
                <p class="bold-text">Ancien mot de passe :</p>
                <p><span><?= $infoUser["Password"] ?></span></p>
            </div>
            <form action="index.php?action=updateDataUser&password" method="post">
                <div class="form-group">
                    <label for="password">Nouveau mot de passe :</label>
                    <input type="password" name="password" id="phone">
                </div>
                <div class="form-group">
                    <label for="password-confirm">Ressaisir le nouveau mot de passe :</label>
                    <input type="password" name="password-confirm" id="password-confirm">
                </div>
                <div class="form-group">
                    <label for="check-password">Mot de passe actuel :</label>
                    <input type="password" name="check-password" id="check-password">
                </div>
                <input class="update-btn input-update" type="submit" value="Enregistrer la modification">
            </form>
        </div>
    </div>
</section>