<form class="form-connect-user" action="index.php?action=loginAdmin" method="post">
    <fieldset>
        <legend>Connexion</legend>
        <div class="container-logo">
            <a href="index.php"><img id="logo" class="logo" src="www/img/LBPI-1.png" alt="logo" /></a>
        </div>
        <div>
            <label for="mail"></label>
            <input type="text" name="email" id="mail" placeholder="E-mail" required>
        </div>
        <div>
            <label for="password"></label>
            <input type="password" name="password" id="password" placeholder="Mot de passe" required>
        </div>
        <input class="btn-submit-form" type="submit" value="Connexion">
    </fieldset>
</form>