<div class="displayProduct">
    <?php foreach ($searchProducts as $product) : ?>
        <div class=" card">
            <div>
                <img class="card-img" src="www/img/images-shop/<?= $product["Photo"] ?>" alt="picture-product-shop">
            </div>
            <div>
                <p class="card-title"><?= $product["Produit"] ?></p>
                <p><?= $product["Description"] ?></p>
            </div>
            <div class="card-price">
                <p><?= $product["Prix"] . "€" ?></p>
                <i class="fas fa-cart-plus"></i>
            </div>
        </div>
    <?php endforeach ?>
</div>