<div class="displayProduct">
    <?php foreach ($searchProducts as $product) : ?>
        <div class=" card">
            <div>
                <img class="card-img" src="www/img/images-shop/<?= $product["Photo"] ?>" alt="picture-product-shop">
            </div>
            <div>
                <p class="card-title"><?= $product["Produit"] ?></p>
                <p><?= $product["Description"] ?></p>
            </div>
            <div class="card-price">
                <p><?= $product["Prix"] . "€" ?></p>
                <div class="container-input-quantity">
                    <label for="input-quantity">Quantité:</label>
                    <input type="number" min="1" max="9" value="0" class="<?= "input-quantity" . $product["ID"] ?>" id="input-quantity">
                </div>
                <button class="add-caddie" data-product="<?= $product["Produit"] ?>" data-description="<?= $product["Description"] ?>" data-price="<?= $product["Prix"] ?>" data-id="<?= $product["ID"] ?>"><i class="fas fa-cart-plus"></i></button>
            </div>
            <div class="small-hidden">
                <small class="<?= "add-text" . $product["ID"] ?>"></small>
            </div>
        </div>
    <?php endforeach ?>
</div>
<script src="www/js/searchBarEvent.js"></script>